### ISSUE TITLE
After installing, I see "No matching autocommands: User tsdetect#detect#node"

### ISSUE THREAD

**Issue by filmaj** [LumaKernel/vim-tsdetect#7]
Thank you for this project. I hope to get it running properly 😄 

I see the following in my status bar after loading a `.ts` file in a node project (though it is not an error, only in statusbar, and only shows sometimes):

<img width="401" alt="Screen Shot 2022-08-26 at 4 03 14 PM" src="https://user-images.githubusercontent.com/52645/186982588-c3ac5ec9-53b4-460f-85ec-2b3a363bd36b.png">

Furthermore, I see the following errors before the buffer opens up when I try to load a `.ts` file from a deno project:

<img width="431" alt="Screen Shot 2022-08-26 at 4 01 24 PM" src="https://user-images.githubusercontent.com/52645/186982336-90ddf019-b817-4202-8260-2093ee511d33.png">

That said, running `:echo b:tsdetect_is_node` returns `1` when I'm in a node project, and `0` when I'm in a deno project - so it seems to be working OK somehow.

I am trying to use this project to conditionally deactivate the `coc-tsserver` extension + activate the `coc-deno` extension when working in a deno project, and vice-versa when working in a node project.

**Comment by filmaj** [comment]
As a workaround, I ended up implementing / stealing from this plugin to get something working in my `.vimrc`, see https://github.com/filmaj/dotfiles/commit/e4bba257c92c338842194e046471fec878293fe1

**Comment by tani** [comment]
A gentle reminder, @LumaKernel. Did you have any plans to solve this?

**Comment by LumaKernel** [comment]
Thank you. I recently updated coc.nvim and I recognize a different problem instead, but I've never seen this issue.
I'm workarounding that by manual CocCommand tsdetect.... for a while.

I'll take time in next two weeks.

**Comment by tani** [comment]
Around two months ago, I faced this issue. That's why I have sent this message.
Now, after the update coc.nvim, I faced another issue which might the same as yours.
I am not sure that the current issue suppressing this issue. 
However, then, after the fix your issue, let's get back to this issue again.

Thank you for working and making this plugin.

**Comment by LumaKernel** [comment]
Supported latest coc.nvim and release as v4.0.0.
Also update coc-deno to latest for the best experience.
After solving the error what I saw, I didn't see the error in this issue , so if you still see the original error, feel free to reopen the issue.
Thank you for the reminder.
